### ISSUE TITLE
build error os x

### ISSUE THREAD

**Issue by intmainreturn00** [dilawar/sound#2]
`src/wav-file.cc:432:20: error: format string is not a string literal (potentially insecure)
      [-Werror,-Wformat-security]
    fprintf(pFile, header);
                   ^~~~~~
src/wav-file.cc:432:20: note: treat the string as an argument to avoid this
    fprintf(pFile, header);
                   ^
                   "%s", 
src/wav-file.cc:434:20: error: format string is not a string literal (potentially insecure)
      [-Werror,-Wformat-security]
    fprintf(pFile, header);
                   ^~~~~~
src/wav-file.cc:434:20: note: treat the string as an argument to avoid this
    fprintf(pFile, header);
                   ^
                   "%s", 
src/wav-file.cc:439:24: error: format string is not a string literal (potentially insecure)
      [-Werror,-Wformat-security]
        fprintf(pFile, data);
                       ^~~~
src/wav-file.cc:439:24: note: treat the string as an argument to avoid this
        fprintf(pFile, data);
                       ^
                       "%s", 
3 errors generated.
`

**Comment by intmainreturn00** [comment]
delete an -Werror  from makefile...

got link error...

`ld: unknown option: -rpath-link
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by intmainreturn00** [comment]
maybe I don't have some dependencies...
maybe it will be good to mention dependencies at readme

**Comment by intmainreturn00** [comment]
well, with this
`CC = g++
CFLAGS = -c -O3 -Wall   -I /usr/local/include 
MACRO =  -D DEBUG #-D SCILAB1 -D SOX
VPATH = src:../include
OBJECTS = main.o wav-file.o 
INCFLAGS = -I include 
LDFLAGS = -Wl,-rpath,/usr/local/lib  #-L/usr/lib/scilab`

it compiles and runs.

**Comment by dilawar** [comment]
Thanks. I'll add cmake based build system. 

⁣Sent from handheld device, pardon my brevity.

**Comment by dilawar** [comment]
Now using cmake to build the project.

**Comment by intmainreturn00** [comment]
cool =)
